### ISSUE TITLE
Not an issue/ need help

### ISSUE THREAD

**Issue by Anirudh0019** [adrianhajdin/yc_directory#25]
# Issue: experimental.ppr can only be enabled on latest version of next.js
Firstly, sorry i couldnt find a discord so have to ask here
### i have been following the yt tutorial on this project and currently at the part where he implements "*ppr*" on the startup page 
However project wont start now because it throws an exception that it would work only with the latest canary version is 15.0.4 , i am currently on 15.0.3, is there  a starightforward way to update to canary? i was thinking of deleting package-lock.json
setting the version   `  "next": "15.0.3"`, to ` "next": "15.0.4"`, and running npm i but not sure if it would help, and i dont want to break it 

could someone guide please(sorry a beginner)
here is the package.json if it helps and the error 
```
{
  "name": "yc-directory",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev ",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "predev": "npm run typegen",
    "prebuild": "npm run typegen",
    "typegen": "sanity schema extract --path=./sanity/extract.json && sanity typegen generate"
  },
  "packageManager": "npm@10.5.2",
  "overrides": {
    "react": "$react",
    "react-dom": "$react-dom"
  },
  "dependencies": {
    "@radix-ui/react-slot": "^1.1.0",
    "@sanity/image-url": "^1.1.0",
    "@sanity/vision": "^3.63.0",
    "@tailwindcss/typography": "^0.5.15",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-react": "^0.456.0",
    "next": "15.0.3",
    "next-auth": "^5.0.0-beta.25",
    "next-sanity": "^9.8.3-canary.1",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106",
    "sanity": "^3.63.0",
    "sanity-plugin-markdown": "^5.0.0",
    "server-only": "^0.0.1",
    "styled-components": "^6.1.13",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```
>Error

```
PS C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory> npm run dev

> yc-directory@0.1.0 predev
> npm run typegen


> yc-directory@0.1.0 typegen
> sanity schema extract --path=./sanity/extract.json && sanity typegen generate

✅ Extracted schema to ./sanity/extract.json
✅ Generated TypeScript types for 14 schema types and 0 GROQ queries in 0 files into: ./sanity/types.ts

> yc-directory@0.1.0 dev
> next dev

C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory\node_modules\next\dist\server\config.js:241
            throw new CanaryOnlyError('experimental.ppr');
                  ^

CanaryOnlyError: The experimental feature "experimental.ppr" can only be enabled when using the latest canary version of Next.js.
    at assignDefaults (C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory\node_modules\next\dist\server\config.js:241:19)
    at loadConfig (C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory\node_modules\next\dist\server\config.js:843:32)
    at async Module.nextDev (C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory\node_modules\next\dist\cli\next-dev.js:190:14)

Node.js v20.16.0
PS C:\Users\aniru\OneDrive\Documents\next-samples\yc-directory> 

```

**Comment by Anirudh0019** [comment]
okay nvm guys sorry, just ran `npm i next@canary` , i think it works now
